### ISSUE TITLE
re-learning how to use CI

### ISSUE THREAD

**Issue by bengland2** [cloud-bulldozer/benchmark-operator#374]
I'm trying to run my PR through the CI using minikube and the CI tests do not pass, even with the master branch.     Is it because I'm using the wrong version of things?  See:

https://pastebin.com/fZbq14xS

is v1.18 too advanced???   The initial error is:

**Comment by bengland2** [comment]
sorry I meant to include:

+ kubectl apply -f resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
The CustomResourceDefinition "benchmarks-7261bebf-b554-4e7c-80e3-fdab53ed798d.ripsaw.cloudbulldozer.io" is invalid:

**Comment by dry923** [comment]
@bengland2 thanks for brining this up. I haven't seen it in my testing. The new ci systems are versions:
```
# oc version
Client Version: 4.5.1
Server Version: 4.5.1
Kubernetes Version: v1.18.3+8b0a82f

# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2-0-g52c56ce", GitCommit:"711c56a65d92d8a61930378670ba92e04a27ef86", GitTreeState:"clean", BuildDate:"2020-07-01T23:11:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+8b0a82f", GitCommit:"8b0a82f", GitTreeState:"clean", BuildDate:"2020-07-10T05:34:00Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

So if anything your client version is a touch behind at v1.18.0. Any chance you can update it and try again?

**Comment by bengland2** [comment]
I did as you asked.   Now the tests/test_fiod.sh runs but when I try to use master branch and a sample CR from :+1: 

resources/crds/ripsaw_v1alpha1_fio_distributed_cr.yaml

I get failure shown at:  https://pastebin.com/cR6E61U3

which is fio core dumping immediately after fio --server is started.

**Comment by bengland2** [comment]
and it's the fio image:

[bengland@localhost ripsaw]$ oc run --rm -it --image quay.io/cloud-bulldozer/fio:latest foo
If you don't see a command prompt, try pressing enter.

[root@foo /]# which fio
/usr/local/bin/fio

[root@foo /]# fio --server
Illegal instruction (core dumped)

and for more details:

[root@foo /]# gdb fio 
GNU gdb (GDB) Red Hat Enterprise Linux 8.2-11.el8
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from fio...done.
(gdb) b main
Breakpoint 1 at 0x40d8a0: file fio.c, line 32.
(gdb) r --server
Starting program: /usr/local/bin/fio --server
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-101.el8.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x000000000040d6f5 in fio_client_hash_init () at client.c:95
95	client.c: No such file or directory.

Which makes no sense:

https://github.com/axboe/fio/blob/master/client.c#L95

**Comment by bengland2** [comment]
so I went and built my own fio image using master branch of snafu, and this one doesn't do what happened above, it works fine.   Fortunately I can substitute my own image for what's in quay.io/cloud-bulldozer using workload_args.image parameter.  Am working with that for now.

**Comment by bengland2** [comment]
I still get errors because of kb_base=1000 in job file.   kb_base=1000 is a really bad idea because most fio job files today are written *assuming* power-of-2 I/O sizes and because O_DIRECT *requires* power-of-2 I/O sizes.  When  I took that out, the errors stopped.

**Comment by bengland2** [comment]
moral of story is use powers of 2 for bs sizes and use KiB not KB.   Also,
