### ISSUE TITLE
With multiple jobs ( numjobs ) only one job writes requested file size ( filesize )

### ISSUE THREAD

**Issue by ekuric** [cloud-bulldozer/benchmark-operator#381]
When running fio with multiple jobs below anomalies are visible 
- fio jobs are not running in paralllel 
- only first fio job writes `filesize` and jobs after do not write requested `filesize` 

Test with single job `numjobs` is [here](https://gist.githubusercontent.com/ekuric/a447de4f94438d942cd0d2634a97c317/raw/bd252d6a7190d72ff0a5840130b91fcd76b02788/gistfile1.txt) test finsihed, file size is `filesize` requested

Test with multiple jobs `numjobs` is [here](https://gist.githubusercontent.com/ekuric/d85acfed378c4ec828f918bb9bd04cbe/raw/7a68d7d9744f9bc820f96040cb9b617581d218b4/multiple%2520fio%2520jobs) 

fio CR [file used ](https://gist.githubusercontent.com/ekuric/374134a19e9b6bea5d2d139acbc0177c/raw/9778c437df870c2a50fff9042ccf99211b1adc4d/cr%2520file%2520used)

**Comment by ekuric** [comment]
//cc @bengland2 @shekharberry @acalhounRH fyi

**Comment by ekuric** [comment]
@shekharberry pointed that 3 jobs each writting 2 GB file cannot fit on 5 Gi storage size, still it should fail and successfully finish.

**Comment by ekuric** [comment]
tried with storage size of 20 GB, test finished, but not all jobs wrote requested `filesize` 

```020-08-04T16:22:19Z - INFO     - MainProcess - run_snafu: logging level is INFO
2020-08-04T16:22:19Z - INFO     - MainProcess - wrapper_factory: identified fio as the benchmark wrapper
2020-08-04T16:22:19Z - INFO     - MainProcess - trigger_fio: Executing fio --client=/tmp/host/hosts /tmp/fiod-e0c75a50-d764-54eb-9bd1-bad6a4c9a452/fiojob-write-4KiB-3/1/write/fiojob --output-format=json --output=/tmp/fiod-e0c75a50-d764-54eb-9bd1-bad6a4c9a452/fiojob-write-4KiB-3/1/write/fio-result.json
2020-08-04T16:22:41Z - INFO     - MainProcess - trigger_fio: fio has successfully finished sample 1 executing for jobname write and results are in the dir /tmp/fiod-e0c75a50-d764-54eb-9bd1-bad6a4c9a452/fiojob-write-4KiB-3/1/write

2020-08-04T16:22:41Z - INFO     - MainProcess - trigger_fio: Executing fio --client=/tmp/host/hosts /tmp/fiod-e0c75a50-d764-54eb-9bd1-bad6a4c9a452/fiojob-write-4KiB-3/2/write/fiojob --output-format=json --output=/tmp/fiod-e0c75a50-d764-54eb-9bd1-bad6a4c9a452/fiojob-write-4KiB-3/2/write/fio-result.json
2020-08-04T16:23:04Z - INFO     - MainProcess - trigger_fio: fio has successfully finished sample 2 executing for jobname write and results are in the dir /tmp/fiod-e0c75a50-d764-54eb-9bd1-bad6a4c9a452/fiojob-write-4KiB-3/2/write

2020-08-04T16:23:04Z - INFO     - MainProcess - trigger_fio: Executing fio --client=/tmp/host/hosts /tmp/fiod-e0c75a50-d764-54eb-9bd1-bad6a4c9a452/fiojob-write-4KiB-3/3/write/fiojob --output-format=json --output=/tmp/fiod-e0c75a50-d764-54eb-9bd1-bad6a4c9a452/fiojob-write-4KiB-3/3/write/fio-result.json
2020-08-04T16:23:26Z - INFO     - MainProcess - trigger_fio: fio has successfully finished sample 3 executing for jobname write and results are in the dir /tmp/fiod-e0c75a50-d764-54eb-9bd1-bad6a4c9a452/fiojob-write-4KiB-3/3/write

2020-08-04T16:23:26Z - INFO     - MainProcess - run_snafu: Duration of execution - 0:01:07, with total size of 169440 bytes
run finished
root@ip-172-31-85-171: ~/elko/ripsaw/resources/crds # oc get pods
NAME                                    READY   STATUS      RESTARTS   AGE
benchmark-operator-64f64fb759-9zmm2     3/3     Running     0          4h25m
fio-client-e0c75a50-7ths7               0/1     Completed   0          99s
fio-server-1-benchmark-e0c75a50-9j25r   1/1     Running     0          2m32s
fio-server-2-benchmark-e0c75a50-rtd4p   1/1     Running     0          2m32s
fio-server-3-benchmark-e0c75a50-kjkhw   1/1     Running     0          2m31s
root@ip-172-31-85-171: ~/elko/ripsaw/resources/crds # for z in $(oc get pods |grep fio-ser |awk '{print $1}' ); do oc exec $z -- ls -l /mnt/pvc ; done 
total 2243284
-rw-------. 1 1000590000 1000590000 2147483648 Aug  4 16:23 10.131.0.7.f.\0.\0
-rw-------. 1 1000590000 1000590000   74924032 Aug  4 16:23 10.131.0.7.f.\1.\0
-rw-------. 1 1000590000 1000590000   74686464 Aug  4 16:23 10.131.0.7.f.\2.\0
drwxrws---. 2 root       1000590000      16384 Aug  4 16:21 lost+found
total 2242980
-rw-------. 1 1000590000 1000590000 2147483648 Aug  4 16:23 10.128.2.12.f.\0.\0
-rw-------. 1 1000590000 1000590000   74633216 Aug  4 16:23 10.128.2.12.f.\1.\0
-rw-------. 1 1000590000 1000590000   74665984 Aug  4 16:23 10.128.2.12.f.\2.\0
drwxrws---. 2 root       1000590000      16384 Aug  4 16:21 lost+found
total 2244612
-rw-------. 1 1000590000 1000590000 2147483648 Aug  4 16:23 10.131.2.16.f.\0.\0
-rw-------. 1 1000590000 1000590000   74993664 Aug  4 16:23 10.131.2.16.f.\1.\0
-rw-------. 1 1000590000 1000590000   75976704 Aug  4 16:23 10.131.2.16.f.\2.\0
drwxrws---. 2 root       1000590000      16384 Aug  4 16:21 lost+found
root@ip-172-31-85-171: ~/elko/ripsaw/resources/crds                                    gp2                     2m53s

root@ip-172-31-85-171: ~/elko/ripsaw/resources/crds # oc get pvc
NAME               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
claim-1-e0c75a50   Bound    pvc-75976664-a630-48be-84bf-034dd0992352   20Gi       RWO            gp2            3m2s
claim-2-e0c75a50   Bound    pvc-1232e6e8-dd49-4065-a820-f62a71234434   20Gi       RWO            gp2            3m1s
claim-3-e0c75a50   Bound    pvc-75dba56d-a928-4a0b-a86e-181ed85eb88e   20Gi       RWO            gp2            3m1s
root@ip-172-31-85-171: ~/elko/ripsaw/resources/crds # for z in $(oc get pods |grep fio-ser |awk '{print $1}' ); do oc exec $z -- df -h |grep pvc  ; done 
/dev/nvme1n1                           20G  2.2G   18G  12% /mnt/pvc
/dev/nvme1n1                           20G  2.2G   18G  12% /mnt/pvc
/dev/nvme2n1                           20G  2.2G   18G  12% /mnt/pvc
root@ip-172-31-85-171: ~/elko/ripsaw/resources/crds # 
```

**Comment by ekuric** [comment]
`write_runtime` is short in default configuration, I change it to 300s and tried 5 jobs in 3 servers, ... still not working, trying without `write_runtime`

 # oc get pods
NAME                                    READY   STATUS      RESTARTS   AGE
benchmark-operator-64f64fb759-9zmm2     3/3     Running     0          17h
fio-client-31e281aa-957dh               0/1     Completed   0          5m39s
fio-server-1-benchmark-31e281aa-ssf42   1/1     Running     0          6m23s
fio-server-2-benchmark-31e281aa-gdphq   1/1     Running     0          6m22s
fio-server-3-benchmark-31e281aa-2q6w9   1/1     Running     0          6m21s
root@ip-172-31-85-171: ~/elko/ripsaw/resources/crds # for z in $(oc get pods |grep fio-ser |awk '{print $1}' ); do oc exec $z -- ls -l /mnt/pvc  ; echo $z;  done  
total 3905336
-rw-------. 1 1000590000 1000590000 2147483648 Aug  5 05:19 10.131.2.7.f.\0.\0
-rw-------. 1 1000590000 1000590000  462991360 Aug  5 05:19 10.131.2.7.f.\1.\0
-rw-------. 1 1000590000 1000590000  462516224 Aug  5 05:19 10.131.2.7.f.\2.\0
-rw-------. 1 1000590000 1000590000  462974976 Aug  5 05:19 10.131.2.7.f.\3.\0
-rw-------. 1 1000590000 1000590000  463060992 Aug  5 05:19 10.131.2.7.f.\4.\0
drwxrws---. 2 root       1000590000      16384 Aug  5 05:13 lost+found
fio-server-1-benchmark-31e281aa-ssf42
total 3909592
-rw-------. 1 1000590000 1000590000 2147483648 Aug  5 05:19 10.131.0.7.f.\0.\0
-rw-------. 1 1000590000 1000590000  464494592 Aug  5 05:19 10.131.0.7.f.\1.\0
-rw-------. 1 1000590000 1000590000  463724544 Aug  5 05:19 10.131.0.7.f.\2.\0
-rw-------. 1 1000590000 1000590000  463101952 Aug  5 05:19 10.131.0.7.f.\3.\0
-rw-------. 1 1000590000 1000590000  464580608 Aug  5 05:19 10.131.0.7.f.\4.\0
drwxrws---. 2 root       1000590000      16384 Aug  5 05:13 lost+found
fio-server-2-benchmark-31e281aa-gdphq
total 3913036
-rw-------. 1 1000590000 1000590000 2147483648 Aug  5 05:19 10.128.2.12.f.\0.\0
-rw-------. 1 1000590000 1000590000  466333696 Aug  5 05:19 10.128.2.12.f.\1.\0
-rw-------. 1 1000590000 1000590000  464171008 Aug  5 05:19 10.128.2.12.f.\2.\0
-rw-------. 1 1000590000 1000590000  463335424 Aug  5 05:19 10.128.2.12.f.\3.\0
-rw-------. 1 1000590000 1000590000  465588224 Aug  5 05:19 10.128.2.12.f.\4.\0
drwxrws---. 2 root       1000590000      16384 Aug  5 05:13 lost+found
fio-server-3-benchmark-31e281aa-2q6w9

**Comment by ekuric** [comment]
with removed `write_runtime` and below workload file, fio-server pods are not starting 

```workload:
      args:
        bs:
        - 4KiB
        filesize: 2GiB
        iodepth: 4
        jobs:
        - write
        log_sample_rate: 3000
        numjobs:
        - 5
        pin_server: ""
        prefill: true
        read_ramp_time: 5
        read_runtime: 15
        samples: 1
        servers: 3
        storageclass: gp2
        storagesize: 20Gi
        write_ramp_time: 5
      name: fio_distributed
```

**Comment by bengland2** [comment]
very relevant!

**Comment by jtaleric** [comment]
Checking here on this issue... is someone going to work on it?

**Comment by jtaleric** [comment]
cc @bengland2 @acalhounRH @ekuric

**Comment by bengland2** [comment]
I just ran with the Filesystem storage class on AWS EC2 i3en and I did not see this problem, I checked file sizes.  But I was using prefill: true.

**Comment by acalhounRH** [comment]
This issue may be due to the pre-fill having hard coded values for numbjobs, will look into addint override functionality to the prefill parameters so they match/generate the same number of files as the workload.
