### ISSUE TITLE
Running fio benchmark without `runtime` option is not working. 

### ISSUE THREAD

**Issue by ekuric** [cloud-bulldozer/benchmark-operator#382]
[fio](https://linux.die.net/man/1/fio) `runtime` option specifies how long specific operation will run, in `ripsaw_v1alpha1_fio_distributed_cr.yaml` we have `write_runtime` and `read_runtime`.
If we want to run test without runtime option ( eg. remove write_runtime from cr ) , ie. letting test to run as long it is necessary to write desired file it will not work - [workload](https://gist.githubusercontent.com/ekuric/f28ea4ff08fc7896d010a3909c462a5e/raw/a05e20e1341d0cccdd1c219090e2f8a731a73239/fio%2520workload%2520without%2520runtime%2520option) will never move out of building state 
``` oc get benchmark 
NAME            TYPE              STATE      METADATA STATE   CERBERUS        UUID                                   AGE
fio-benchmark   fio_distributed   Building   not collected    not connected   e610548d-ea97-500c-8350-3af68605ceeb   4m3s
```

**Comment by rsevilla87** [comment]
Hey @ekuric, removing all references to run time should do the trick:
```
      - runtime={{ workload_args.write_runtime }}
      - runtime={{ workload_args.read_runtime }}
```

**Comment by ekuric** [comment]
Maybe we have to distinguish `radndwrite_runtime` `randrw_runtime` and `write_runtime` as having anywhere in cr file `workload_args.read_runtime ` will leave it to hang. Same for `read_runtime`

**Comment by bengland2** [comment]
There is a reason why we have the runtime parameter - prefill: true is normally the only fio activity with unbounded time, because it can take forever to populate a huge file with 4-KB random writes, for example.
