### ISSUE TITLE
Need to add ppc64le images for ripsaw workloads 

### ISSUE THREAD

**Issue by piyushgupta1551** [cloud-bulldozer/benchmark-operator#387]
Need to add ppc64le images for ripsaw workloads so that this repo support both x86 and ppc64le archs by default.
Travis Support (Would need a possible discussion) can be a possible way ahead. Changes would be needed to snafu/benchmark-wrapper (https://github.com/cloud-bulldozer/benchmark-wrapper) and ripsaw/benchmark-operator (https://github.com/cloud-bulldozer/benchmark-operator) repositories.

**Comment by jtaleric** [comment]
Still relevant.

**Comment by piyushgupta1551** [comment]
Relevant Issue - https://github.com/cloud-bulldozer/benchmark-wrapper/issues/228
