### ISSUE TITLE
check_es.py gets privilege error when run from my laptop

### ISSUE THREAD

**Issue by bengland2** [cloud-bulldozer/benchmark-operator#408]
When I try to run tests/test_fiod.sh from my laptop, I get the error in [this pastebin](https://pastebin.com/ua9v3S8p).  The relevant part is
```
elasticsearch.exceptions.AuthorizationException: AuthorizationException
(403, 'security_exception', 'action [indices:admin/refresh] is unauthorized for user [snafu]')
```
So there was a call added to tests/check_es.py  
```
    es.indices.refresh(index=index)
```
That is causing this error (Thx @jtaleric ).   The line was added by @rsevilla87 .   When you remove this line, the test passes.   However, this is not in the equivalent benchmark-wrapper/ci/check_es.py script.   (Why can't snafu CI use the check_es.py script in benchmark-operator, since it clones it?).   Anyway,  the point is: do we really need to refresh the indexes every time we run check_es.py?     Maybe we do, I don't know.   If we do, don't we need to add this priv to the snafu user in the ES server so that anyone can run the CI test?   Not sure why the CI itself doesn't hit this problem.

**Comment by dry923** [comment]
@bengland2 So a few comments in no particular order:
- The benchmar-wrapper/ci/check_es.py script is no longer used. We currently only use the one in benchmark-operator. I can take an AI to remove the old file and function.
- The refresh was added because we were constantly getting failures from the check script because the data wasn't available in ES yet. By adding that command it consistently works when the data is indexed.
- I'm not sure what the privilege problem is TBH. It has been executing in this fashion for months and we have not seen any issue from it.

**Comment by rsevilla87** [comment]
@bengland2 you're using the check_es.py with the production ES instance and this script is meant to be used from the CI.

**Comment by bengland2** [comment]
again, it doesn't say in the docs.   We need to tell developers how they are supposed to do this.  I searched a CI log and found:
```
export ES_SERVER=search-cloud-perf-lqrf3jjtaqo7727m7ynd2xyt4y.us-west-2.es.amazonaws.com
```
That hardly looks like it's cast in stone.   where does this come from?   So how are people supposed to know?   Are they supposed to set up their own ES server or use this one?   When setting up an ES server, what is the relevant privilege that they need to add?   I didn't find it in kibana.   

re: "I'm not sure what the privilege problem is TBH. It has been executing in this fashion for months and we have not seen any issue from it".  
The error is highly reproducible with the production server.   Would a default setup for ES cause this problem?    

should there be DNS CNAME entries defined that point to the production server and the CI server?   That way, you can change where they really live without disrupting source code, and you can document where these ES servers are using the CNAMEs.

**Comment by jtaleric** [comment]
> again, it doesn't say in the docs. We need to tell developers how they are supposed to do this. I searched a CI log and found:
> 
> ```
> export ES_SERVER=search-cloud-perf-lqrf3jjtaqo7727m7ynd2xyt4y.us-west-2.es.amazonaws.com
> ```
> 
> That hardly looks like it's cast in stone. where does this come from? So how are people supposed to know? Are they supposed to set up their own ES server or use this one? When setting up an ES server, what is the relevant privilege that they need to add? I didn't find it in kibana.
> 

IMHO, yes. Users outside of RH should be deploying and maintaining their own ES server. 

> re: "I'm not sure what the privilege problem is TBH. It has been executing in this fashion for months and we have not seen any issue from it".
> The error is highly reproducible with the production server. Would a default setup for ES cause this problem?

No. A default ES setup would basically let the world write/read/delete/blowup... Hence our production ES server being a bit more picky. 

> 
> should there be DNS CNAME entries defined that point to the production server and the CI server? That way, you can change where they really live without disrupting source code, and you can document where these ES servers are using the CNAMEs.

meh - maybe... Eventually? We don't really have staff to maintain our resource today. We have replication from our Public Prod ES instance to our internal instance... However, the distinction of prod vs testing isn't clear.

**Comment by bengland2** [comment]
OK, well in that case, this issue will serve to document how the system works today and keep people from getting confused about this error like I was.
