### ISSUE TITLE
Feature requests: fio json output retrieval, fio librados and librbd

### ISSUE THREAD

**Issue by fritchie** [cloud-bulldozer/benchmark-operator#417]
Feature Requests

1. The fio-client pod goes to a "Completed" status when the fio job is finished. This makes it difficult to
copy the fio json files from /tmp when elasticsearch is not available. An option to keep the fio-client pod running after the job is complete would be nice to have for this situation. Another option would be to have all the json output sent to the pod log as is done for the prefill job.

2. It would be nice to be able to test ceph performance using the librados and librbd fio io engines. Is this something you would be willing to integrate? The fio-server pods would need a valid ceph keyring and ceph.conf file.

**Comment by jtaleric** [comment]
@fritchie Agreed - having a better option for results versus always relying on Elasticsearch. 

@acalhounRH I wonder if we could send result data to our redis backend, and have Ripsaw present the user with results after the run? Since we know the workload has completed?

**Comment by bengland2** [comment]
+1.   However, if you send result to redis, how do results get cleaned up?   If JSON is in the log, it's easy to write a python script that digs it out of the log, and then you can do whatever you want with it.  However, it would be so big that it would make the log harder to read.  Example: the prefill JSON output.

**Comment by fritchie** [comment]
@bengland2 for cleaning up redis I believe it is possible to set an expire time on a key (I have never personally used this though):

https://redis.io/commands/expire
