### ISSUE TITLE
pbench-uperf fails to install in client vmi

### ISSUE THREAD

**Issue by sarahbx** [cloud-bulldozer/benchmark-operator#429]
It appears the installation process in the client for pbench-uperf has changed, possibly due to the move to RHEL8 for the underlying image. I attempted to use the method described in the pbench docs, but kept running into dependency issues. https://distributed-system-analysis.github.io/pbench/start.html

Template file: `roles/uperf/templates/workload_vm.yml.j2`

From console output of the client vmi during an attempted run:

`Error: Unable to find a match: pbench-uperf`
```
uperf-client-10 login: [   22.513820] cloud-init[800]: Fedora Modular 32 - x86_64                      3.4 MB/s | 4.9 MB     00:01
[   24.311706] cloud-init[800]: Fedora Modular 32 - x86_64 - Updates            3.6 MB/s | 3.7 MB     00:01
[   29.327551] cloud-init[800]: Fedora 32 - x86_64 - Updates                    5.4 MB/s |  23 MB     00:04
[   38.783810] cloud-init[800]: Fedora 32 - x86_64                               23 MB/s |  70 MB     00:03
[   62.030593] cloud-init[800]: Package dnf-plugins-core-4.0.14-1.fc32.noarch is already installed.
[   62.950511] cloud-init[800]: Dependencies resolved.
[   62.974947] cloud-init[800]: Nothing to do.
[   62.975053] cloud-init[800]: Complete!
[   63.908170] cloud-init[800]: Repository successfully enabled.
[   66.065190] cloud-init[800]: Copr repo for pbench owned by ndokos            5.0 kB/s | 9.4 kB     00:01
[   68.634738] cloud-init[800]: No match for argument: pbench-uperf
[   68.658054] cloud-init[800]: Package python3-pip-19.3.1-2.fc32.noarch is already installed.
[   68.711585] cloud-init[800]: Error: Unable to find a match: pbench-uperf
[   69.848966] cloud-init[800]: WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
[   70.499126] cloud-init[800]: Collecting pip
[   71.631323] cloud-init[800]:   Downloading https://files.pythonhosted.org/packages/4e/5f/528232275f6509b1fff703c9280e58951a81abe24640905de621c9f81839/pip-20.2.3-py2.py3-none-any.whl (1.5MB)
[   73.278417] cloud-init[800]: Installing collected packages: pip
[   74.098061] cloud-init[800]: Successfully installed pip-20.2.3
[   74.787011] cloud-init[800]: WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
[   74.791660] cloud-init[800]: Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
[   74.796093] cloud-init[800]: To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
[   75.152764] cloud-init[800]: Collecting elasticsearch<=7.0.2,>=6.0.0
[   75.513075] cloud-init[800]:   Downloading elasticsearch-7.0.2-py2.py3-none-any.whl (83 kB)
[   75.750692] cloud-init[800]: Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.8/site-packages (from elasticsearch<=7.0.2,>=6.0.0) (1.25.7)
[   75.801237] cloud-init[800]: Installing collected packages: elasticsearch
[   75.931383] cloud-init[800]: Successfully installed elasticsearch-7.0.2
[   76.004459] cloud-init[800]: /var/lib/cloud/instance/scripts/runcmd: line 7: git: command not found
[   76.020340] cloud-init[800]: /tmp/uperf_script/run_script.sh: line 10: redis-cli: command not found
[   76.025735] cloud-init[800]: /tmp/uperf_script/run_script.sh: line 10: redis-cli: command not found
[   76.029702] cloud-init[800]: /tmp/uperf_script/run_script.sh: line 10: redis-cli: command not found
```

**Comment by jtaleric** [comment]
Yeah, we were using the pbench-uperf RPM, which seems is no longer in that copr repo.

For our container image, i think `uperf` is in the appstream as `uperf`...
```
COPY snafu/image_resources/centos8-appstream.repo /etc/yum.repos.d/centos8-appstream.repo
RUN dnf install -y --nodocs redis --enablerepo=centos8-appstream && dnf clean all
RUN dnf install -y --nodocs hostname procps-ng iproute net-tools ethtool nmap iputils https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && dnf clean all
RUN dnf install -y uperf && dnf clean all
```

I wonder if we just need to update these lines[1][2] to pull in the appstream and install `uperf` instead of `pbench-uperf`.

[1] https://github.com/cloud-bulldozer/benchmark-operator/blob/master/roles/uperf/templates/workload_vm.yml.j2#L75-L77
[2] https://github.com/cloud-bulldozer/benchmark-operator/blob/master/roles/uperf/templates/server_vm.yml.j2#L61-L63

**Comment by rsevilla87** [comment]
Hey @sarahbx, we're currently using EPEL to install UPerf, so basically you'd have to do something like this.
```
dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm  && dnf install -y uperf 
```
I'm gonna open a PR to fix this issue.

Thanks for reporting!

**Comment by sarahbx** [comment]
Thank you @rsevilla87!

**Comment by rsevilla87** [comment]
Hi @sarahbx, https://github.com/cloud-bulldozer/benchmark-operator/pull/431 should fix this issue. I don't have currently a CNV env available, so I built a new benchmark-operator image using the bits from the PR at quay.io/rsevilla/benchmark-operator:fix-vm . Mind you try it and verify it works properly so we can merge the PR?

**Comment by sarahbx** [comment]
Hi @rsevilla87, have a working environment to look at this, uperf did get installed, but now `git` is not :D 
```
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Collecting git+https://github.com/cloud-bulldozer/benchmark-wrapper
  Cloning https://github.com/cloud-bulldozer/benchmark-wrapper to /tmp/pip-req-build-2vk7uugn
  Running command git clone -q https://github.com/cloud-bulldozer/benchmark-wrapper /tmp/pip-req-build-2vk7uugn
  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/cloud-bulldozer/benchmark-wrapper /tmp/pip-req-build-2vk7uugn
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
```
```
[fedora@uperf-client-10 ~]$ which git
/usr/bin/which: no git in (/home/fedora/.local/bin:/home/fedora/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
```

**Comment by rsevilla87** [comment]
> Hi @rsevilla87, have a working environment to look at this, uperf did get installed, but now `git` is not :D
> 
> ```
> WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
> Collecting git+https://github.com/cloud-bulldozer/benchmark-wrapper
>   Cloning https://github.com/cloud-bulldozer/benchmark-wrapper to /tmp/pip-req-build-2vk7uugn
>   Running command git clone -q https://github.com/cloud-bulldozer/benchmark-wrapper /tmp/pip-req-build-2vk7uugn
>   ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/cloud-bulldozer/benchmark-wrapper /tmp/pip-req-build-2vk7uugn
> ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
> ```
> 
> ```
> [fedora@uperf-client-10 ~]$ which git
> /usr/bin/which: no git in (/home/fedora/.local/bin:/home/fedora/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
> ```

Thanks for bringing this up @sarahbx , I've pushed a new benchmark-operator container image with a fix for that  at `quay.io/rsevilla/benchmark-operator:latest`

Mind you verify it works before merging the patch?

Thanks!

**Comment by sarahbx** [comment]
The new image fixes the installation process @rsevilla87 🙂 
Thank you!
