### ISSUE TITLE
Benchmark CRs do not have common state definitions

### ISSUE THREAD

**Issue by whitleykeith** [cloud-bulldozer/benchmark-operator#449]
Not all benchmark CRs expose the same state definitions which makes it difficult to handle benchmarks in a uniform way. 

The vast majority of the workloads have 3 general states: Building, Running, and Complete. Some workloads may have more than those 3 states (i.e. fiod has StartingServers/StartingClient), but that's fine as they still implement the core 3 states. 

However, some benchmarks do not implement those 3 states which makes it difficult to handle the benchmarks in a programmatic fashion. For example,

hammerdb: "Complete" state maps to "DB Workload Complete"
stressng: "Running" maps to "Benchmark running"

Since these benchmarks use the same CRD, they should share the same state definition.

**Comment by dry923** [comment]
While I do agree we can standardize some of the states it really isn't simple to distill it down to a common 3 or something of the like. If you look in the individual roles those states correspond to varying stages of the workload. For example, ycsb has a load and a run option so there is separation there that is necessary

**Comment by whitleykeith** [comment]
I agree that extra steps can be a different state, like the fiod example. It's just the "core" states need to have common namings. It's similar to normal K8s Pods, which *can* have init steps, but they still *must* have Running/Failed states. 

To me the FIOD states are perfectly fine

Building -> StartingServers -> StartingClient -> Running  -> Complete | Failed

But for instance the hammerdb isn't 

Starting -> Running -> DB Workload Complete

Realistically the ask here is that "all benchmark types must implement a Running, Complete, and Failed state. They can implement more than that, but they must implement those"
