### ISSUE TITLE
Refactor deploy manifests

### ISSUE THREAD

**Issue by whitleykeith** [cloud-bulldozer/benchmark-operator#451]
Currently deploying the operator requires you to run these three commands

```
kubectl apply -f resources/namespace.yaml
kubectl apply -f deploy
kubectl apply -f resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
```

Which is cumbersome and makes it difficult to understand what is needed for the operator to deploy. Ideally, this should just be:

`kubectl apply -f deploy`

**Comment by dry923** [comment]
I agree. The install process should be a bit less chaotic.
