### ISSUE TITLE
Question: benchmark-operator-kube clusterrole

### ISSUE THREAD

**Issue by fritchie** [cloud-bulldozer/benchmark-operator#467]
What is the clusterrole with name benchmark-operator-kube used for? I cannot find any references in the code.

The clusterrole is defined in file:

https://github.com/cloud-bulldozer/benchmark-operator/blob/master/deploy/40_cluster_role_kubevirt.yaml

**Comment by jtaleric** [comment]
hey @fritchie if you are running with cnv/kubevirt that role is needed.
