### ISSUE TITLE
[Uperf] Control Ports used by uperf

### ISSUE THREAD

**Issue by smalleni** [cloud-bulldozer/benchmark-operator#474]
Currently uperf uses port 20000 for the TCP control port, but picks random port numbers for the dataplane traffic. Depending on the number of threads in the test, we should be able to template out corresponding port numbers on the uperf xml, to have a deterministic assignment of port numbers that we can later use to enable networkpolicy.

**Comment by jtaleric** [comment]
@mohit-sheth I thought we had some ideas on this one?
