### ISSUE TITLE
[uperf] Enable Network Policy based on protocol/port numbers

### ISSUE THREAD

**Issue by smalleni** [cloud-bulldozer/benchmark-operator#475]
Currently we have support for a simple network policy that I added based on podselectors. Once we have a determinism in terms of the ports used by uperf, we should create a NetworkPolicy that only enables those ports for that particular type of traffic on the ingress (TCP/UDP and port numbers). This issue depends on
https://github.com/cloud-bulldozer/benchmark-operator/issues/474

**Comment by rsevilla87** [comment]
Creating a Network policy to match only the required ports will increase workload complexity, I'm not sure if it will worth the effort in terms of performance difference compared with the current network policy implementation (all ports from pods matching the selector are open).
Im saying this because east-west network packets will go through the same OFlow tables regardless we allow only some ports or all of them.

**Comment by HughNhan** [comment]
I tend to agree with @rsevilla87 - k8s network policy as I understand is just a simple match of dest_ip, port and proto with action of drop/pass, a ACL feature. For OVS based, the processing overhead is in the OVS control plane. When a new flow arrives, the first packet is punted to OVS control plane where the packet is subjected to as many tables as features are configured on this interface. Once the flow has been processed, a match and action will be programmed to OVS dataplane/DP. Subsequent packets of this flow will be switched by OVS DP. All flows are switched in DP at almost the same overhead (except for special cases where packet may detour to kernel to leverage kernel features like ipsec, and then come back into OVS DP).

So with the overhead being flow processing (and not packet processing), network policy will impact flow-per-second rates only. And with network policy being just simple ACL, I suspect this overhead is almost the same as no network policy. 

IMO, we should try to confirm this requirement by hand and see if there are any unexpected/interesting performance characteristics before pursuing with adding code to the benchmark
