### ISSUE TITLE
Feature request: object storage performance testing 

### ISSUE THREAD

**Issue by fritchie** [cloud-bulldozer/benchmark-operator#479]
Is anyone currently working on adding an object storage performance workload (cosbench/warp/hsbench) or would that be something new to contribute?

**Comment by jtaleric** [comment]
> Is anyone currently working on adding an object storage performance workload (cosbench/warp/hsbench) or would that be something new to contribute?

This would be new. 

I am familiar with cosbench but not the others. Happy for someone to contribute that.

**Comment by fritchie** [comment]
fio also has an http ioengine:

https://github.com/axboe/fio/blob/master/examples/http-s3.fio

This would be very easy to add to the current fio_distributed ansible role by creating a new configmap and a few variables. The gotcha seems to be that the filename_format would be something like

filename_format=/{{workload_args.http_s3_bucket}}/fio-object.${HOSTNAME}.$jobnum

instead of

filename_format=f.\$jobnum.\$filenum

which testing shows is incompatible with the fio wrapper:

https://github.com/cloud-bulldozer/benchmark-wrapper/blob/ab94b45c644cb0015a64661a32588d584e81b181/snafu/fio_wrapper/trigger_fio.py

Not sure if updating the trigger_fio.py script would be more work than adding a new workload for cosbench.

**Comment by bengland2** [comment]
fio is not intended for object storage benchmarks, don't use that.   Talk
to Shekhar Berry, he has a OCS S3 COSBench-based benchmark.  Let me know if
you have trouble getting that into benchmark-operator.

**Comment by jtaleric** [comment]
opening back up

**Comment by bengland2** [comment]
I was on PTO last week, but [I'm working on it](https://docs.google.com/document/d/1biq61C8EGMY4U2Jxd4-kmYtOAUZeY5n3Q3adUb4JQe4/edit).
