### ISSUE TITLE
benchmark operator pod for power64 and Z platform

### ISSUE THREAD

**Issue by vasukulkarni** [cloud-bulldozer/benchmark-operator#480]
Since we are running benchmarks via ripsaw, we need i to work on power64 and Z platform, original issue is: https://github.com/red-hat-storage/ocs-ci/issues/3362

**Comment by vasukulkarni** [comment]
Linking similar issue: https://github.com/cloud-bulldozer/benchmark-wrapper/issues/228

**Comment by jtaleric** [comment]
Hey @vasukulkarni ! We will discuss how we can make this possible with people who have access to ppc/z hardware, to insure we do not introduce any issues with future builds. 

https://coreos.slack.com/archives/CNKHL6076/p1605811724484900

**Comment by jtaleric** [comment]
linking : https://github.com/cloud-bulldozer/benchmark-operator/issues/387
