### ISSUE TITLE
Oudated link on the RipSaw in Operatorhub.io

### ISSUE THREAD

**Issue by amej** [cloud-bulldozer/benchmark-operator#500]
Section 'Links' under https://operatorhub.io/operator/ripsaw points to a dead link https://www.ripsaw.cloudbulldozer.io/
![image](https://user-images.githubusercontent.com/2050992/102074697-2928fd00-3e2b-11eb-8133-02f09aadb033.png)

**Comment by jtaleric** [comment]
Thanks @amej - the work in OperatorHub is sorely outdated.

**Comment by amej** [comment]
@jtaleric : Besides the link; is the operator version available through OperatorHub way behind the one available in github ?
