### ISSUE TITLE
Add `TestPMD` to the tools

### ISSUE THREAD

**Issue by williamcaban** [cloud-bulldozer/benchmark-operator#506]
Consider the addition of `testpmd` to the suite of testing tools. TestPMD is used to test the performance of DPDK applications.

References:

- Testing DPDK Performance and Features with TestPMD: https://software.intel.com/content/www/us/en/develop/articles/testing-dpdk-performance-and-features-with-testpmd.html

**Comment by jtaleric** [comment]
@williamcaban are you interested in adding this functionality?

**Comment by mukrishn** [comment]
@jtaleric I am working on this.

**Comment by smalleni** [comment]
Initial PR opened by Murali: https://github.com/cloud-bulldozer/benchmark-operator/pull/510

**Comment by jtaleric** [comment]
Closed with #510
