### ISSUE TITLE
Image references are using tags instead of digest - unable to use OLM in a disconnected environment

### ISSUE THREAD

**Issue by vandammesander** [cloud-bulldozer/benchmark-operator#519]
in the operator definition the redis image is hardcoded to k8s.gcr.io/redis:v1
As we are using the operator also in disconnected/restricted environments, this will not work.

Please update this reference so it can be used in an olm disconnected environment (for example make it possible to use ImageContentSourcePolicy - in other words an image digest should be used instead of a tag)

**Comment by jtaleric** [comment]
Not sure how the disconnected envs work, but could you just update the spec here?

https://github.com/cloud-bulldozer/benchmark-operator/blob/master/resources/operator.yaml#L64-L76

**Comment by vandammesander** [comment]
Well when using the OLM (operator lifecycle manager) in OKD/OpenShift/K8S you are using the images available via the operatorhub catalog (https://operatorhub.io/operator/ripsaw). We cannot override the images baked in the images themselves. the only way of overriding is via the ImageContentSourcePolicy object where you can define the mirror "offline" registry. As the ImageContentSourcePolicy object only overrides images referencing the digest (direct sha:x reference) we cannot use it with the one on the benchmark-operator.
More info on OLM: https://docs.openshift.com/container-platform/4.6/operators/understanding/olm/olm-understanding-olm.html
More info about OLM in restricted networks: https://docs.openshift.com/container-platform/4.6/operators/admin/olm-restricted-networks.html

Important snippet I am referring to: 

  | While OLM can manage Operators from local sources, the ability for a given Operator to run successfully in a restricted network still depends on the Operator itself. The Operator must:List any related images, or other container images that the Operator might require to perform their functions, in the relatedImages parameter of its ClusterServiceVersion (CSV) object.Reference all specified images by a digest (SHA) and not by a tag.See the following Red Hat Knowledgebase Article for a list of Red Hat Operators that support running in disconnected mode:https://access.redhat.com/articles/4740011
-- | --

**Comment by jtaleric** [comment]
Maybe you can help with a patch to further explain what you are looking for?
