### ISSUE TITLE
Uperf & stressng issues

### ISSUE THREAD

**Issue by ebattat** [cloud-bulldozer/benchmark-operator#520]
Issue 1: stressng: benchmark operator collection did not work

cat benchmark-operator/resources/crds/ripsaw_v1alpha1_stressng_cr.yaml
when collection: true
error: see slide 9 
https://docs.google.com/presentation/d/13Uxzt_u-fv0mZ628mMxb9RRdNVC_21IxCpG0EkEy_c0/edit?usp=sharing

solution:
collection: false

Issue 2: uperf:  class_name did not work
cat benchmark-operator/resources/crds/ripsaw_v1alpha1_uperf_cr.yaml
when enable runtime_class: class_name
error: see slide 5 
https://docs.google.com/presentation/d/13Uxzt_u-fv0mZ628mMxb9RRdNVC_21IxCpG0EkEy_c0/edit?usp=sharing

solution:
disable #runtime_class: class_name

Issue 3: uperf_vm
cat benchmark-operator/resources/crds/ripsaw_v1alpha1_uperf_vm.yaml
when running with <user> got error, please remove the <> from the example.
error: see slide 7
https://docs.google.com/presentation/d/13Uxzt_u-fv0mZ628mMxb9RRdNVC_21IxCpG0EkEy_c0/edit?usp=sharing

Issue 4: (This recommendation in all crds - delete elasticsearch url from all the examples)
cat benchmark-operator/resources/crds/ripsaw_v1alpha1_uperf_cr.yaml
  elasticsearch:
    url: http://es.server.com:80 => url: ""
when run the elasticsearch with example url got error
error: see slide 2
https://docs.google.com/presentation/d/13Uxzt_u-fv0mZ628mMxb9RRdNVC_21IxCpG0EkEy_c0/edit?usp=sharing

**Comment by rsevilla87** [comment]
Hey @ebattat, thanks for raising this up, I've created a PR to address the first and third issues.

How did you reproduce the second issue?, the CR you pointed `benchmark-operator/resources/crds/ripsaw_v1alpha1_uperf_cr.yaml` does not contain any reference to runtime_class

Regarding the 4th issue. As mentioned previously, these CRs are just examples that could be used as a reference, so in case you don't have a ES instance, it's on you to to remove those references from the CR.

**Comment by ebattat** [comment]
Hi Raul,

You're right, runtime_class is appearing only in the readme
<https://github.com/cloud-bulldozer/benchmark-operator/blob/master/docs/uperf.md>,
I think that we need to comment it out because that causes an error or to
fix it.
Regarding the elasticsearch URL, I think we should leave it empty otherwise
it causes an error specially for beginners.
Please let me know if you need more information.

Best Regards,
Eli Battat.

**Comment by ebattat** [comment]
Hi,

You can close this issue, all was fixed.

Best regards,
Eli Battat.
