### ISSUE TITLE
Disconnected environments?

### ISSUE THREAD

**Issue by djohnston89** [cloud-bulldozer/benchmark-operator#530]
Is this operator capable of hardcoding a custom image location like the fio-distributed test does (https://github.com/cloud-bulldozer/benchmark-operator/blob/4e025c572a59d4b9e6b2ddd4c2c6da0b0a091db5/docs/fio_distributed.md#understanding-the-cr-options)?

Our testing environments for our customers require fully restricted networks and proxy environments.

**Comment by jtaleric** [comment]
For the Operator image? 

You could specify that here: 
https://github.com/cloud-bulldozer/benchmark-operator/blob/master/resources/operator.yaml#L37-L76

**Comment by jtaleric** [comment]
@djohnston89 Thoughts on above?

**Comment by djohnston89** [comment]
Yes, thank you. That covers the operator image, but should we worried about any other internet dependencies? ie. I already see the redis image, and I imagine there's more throughout the repo? @jtaleric

**Comment by bengland2** [comment]
do grep -r quay.io . , you'll see a lot of other images being pulled from
quay.   Ignore the ones that are "default", because those can be overridden
in the CR (workload specification).   The ones that matter are the
hardcoded ones, and if your benchmark doesn't require them, then it doesn't
matter.

**Comment by jtaleric** [comment]
sure - however, each of the workloads allow the image to be overwritten, and we have all of our Dockerfiles here[1]. So the user could build them and push to their own repo, does that suffice?

[1] https://github.com/cloud-bulldozer/benchmark-wrapper/tree/master/snafu

**Comment by jtaleric** [comment]
@djohnston89 is this something we can work together on how to run benchmark-operator in a disconnected environment? Possibly add it to our documentation?

**Comment by djohnston89** [comment]
Apologies on my late response. Yes, I do believe that this disconnected capability should be documented and perhaps even allow an environment variable or config file for the customer to provide their private container repo hostname for a more automated way of implementing.
