### ISSUE TITLE
Paralell UPERF sessions

### ISSUE THREAD

**Issue by HughNhan** [cloud-bulldozer/benchmark-operator#532]
In scale test environment, we would like to be able to launch multiple UPERF sessions in parallel to speed up scale tests.
For example, with carefully partitioning, we can setup multiple worker node sets. Each set can run its own tests.
One of the implementation code points that prevents parallel sessions today is the redis variable for the operator and client workload pod communication. This var has fixed name 'redis-start'.  If this name can be enhanced to something like 'redis-{{'session-number}}'-start, the operator and the client pods of the same UPERF session can run w/o interfering with other sessions.  This enhancement should be followed AFTER the uperf scale PR.

**Comment by jtaleric** [comment]
we could use the `{{uuid}}-start` versus having yet another session id.

**Comment by HughNhan** [comment]
I have added this enhancement as part of another commit a while ago
