### ISSUE TITLE
New Workload: Can we add new workload - MMTests

### ISSUE THREAD

**Issue by asispatra** [cloud-bulldozer/benchmark-operator#534]
Can we add new workload - [MMTests](https://github.com/gormanm/mmtests)?

[MMTests](https://github.com/gormanm/mmtests) is a configurable test suite that runs performance tests against arbitrary workloads. It has a lot of workloads. 

It would be better if we focus only one or two from MMTests e.g., [`wptlbflush`](https://github.com/gormanm/mmtests/tree/master/shellpack_src/src/wptlbflush), [`squlite`](https://github.com/gormanm/mmtests/tree/master/shellpack_src/src/sqlite), [`pgioperf`](https://github.com/gormanm/mmtests/tree/master/shellpack_src/src/pgioperf) etc. for now. Later we can include as per need basis. 

Thanks.

**Comment by jtaleric** [comment]
Hey @asispatra - Happy to accept a PR adding MMTests, this isn't on our radar at the moment.
