### ISSUE TITLE
[RFE] Capture and store system metrics for workloads

### ISSUE THREAD

**Issue by jtaleric** [cloud-bulldozer/benchmark-operator#542]
**Is your feature request related to a problem? Please describe.**
Nope, this is purely an enhancement.

**Describe the solution you'd like**
Today the `benchmark-operator` using `benchmark-wrapper` sends workload results to Elasticsearch. However, the only workload that sends Prometheus metrics (system metrics) to Elasticsearch is `kube-burner`. 

kube-burner also supports querying and indexing results without running a workload. 

The idea is to have kube-burner as a side-car container to benchmark-operator, create a simple API to kube-burner to accept start/end/metrics.yaml. 

`start` - when the workload started from benchmark-operator
`end` - when the workload completed
`metrics.yaml` - Each workload we will define a set of metrics we want to capture... There are obvious metrics we will capture with all workloads (CPU/Memory/Network/Disk) -- however there should be more targeted metrics for each workloads (ie, fio w/o OCS and fio w/ OCS). 

**Describe alternatives you've considered**
Prometheus `remote_write` with Elasticsearch. This seems like a viable solution, however we would either need to enable/disable this feature when the workload starts/ends or just stream the results during the duration of all workloads. 

We prefer to have a more targeted collection versus streaming tons of metrics in.

**Comment by rsevilla87** [comment]
Good idea @jtaleric, I think we could start with a "basic" metric profile holding the system metrics you mentioned (CPU/Memory/Network/Disk) and also give the users the option of using it's own profile.
