### ISSUE TITLE
Keep benchmark-operator workload running on infinite loop? Fio-test cronjob vs job

### ISSUE THREAD

**Issue by djohnston89** [cloud-bulldozer/benchmark-operator#543]
**Is your feature request related to a problem? Please describe.**
For our use case, we want to have fio tests running forever on a fixed interval. Not sure how to do this with the "sample" parameter.

**Describe the solution you'd like**
Can fio test create a k8s cronjob instead of a job?

**Describe alternatives you've considered**
Custom tooling that won't fit use case.

**Comment by rsevilla87** [comment]
Hi @djohnston89, this is in my opinion a very specific test scenario that benchmark-operator doesn't cover and I think it shouldn't cover it
I'd suggest you to implement it outside of benchmark-operator. You have several options, one could be the following.
A linux cronjob or systemd timer that periodically creates a FIO benchmark.

**Comment by djohnston89** [comment]
Understood and thank you!
