### ISSUE TITLE
[RFE] Implement pprof collection in kube-burner benchmark

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/benchmark-operator#562]
**Is your feature request related to a problem? Please describe.**
We need to collect pprof information from several golang components such as kube-apiserver, kube-controller-manager and etcd

**Describe the solution you'd like**
Kube-burner has a mechanism to periodically collect this information using Bearer tokens to authenticate with this components. As described in the official docs:
https://kube-burner.readthedocs.io/en/latest/measurements.html#pprof-collection

The main downside of this mechanism is that etcd does not support bearer token authentication. It only supports certificate auth. This is something I'll have to fix in kube-burner if we choose it to perform this task.

Also, kube-burner collects this files and puts them all in a directory, we'll need to implement another mechanism to take this files out from the cluster. e.g.
```shell
kube-burner init -c config.yml
for f in pprof/*;
    curl -X PUT -d @f https://external.repo.com/UUID/
done
```

**Comment by jtaleric** [comment]
Or we could use Snappy to capture the output files.

**Comment by rsevilla87** [comment]
Update: kube-burner support for certificate authentication: https://github.com/cloud-bulldozer/kube-burner/pull/75
