### ISSUE TITLE
Add looped matrix execution to the log generator workload

### ISSUE THREAD

**Issue by dustinblack** [cloud-bulldozer/benchmark-operator#574]
Many (most?) other benchmark-operator workloads employ lists for parameters in the CR files and nested loops, mostly managed via jinja2 in templates, in order to execute large matrices of tests across every unique parameter combination. The log generator workload currently only allows for single values for each parameter.

**Comment by dry923** [comment]
@dustinblack we could certainly look into adding that (it should be a fairly trivial lift). Would you be looking to loop on anything besides the message size?

**Comment by dustinblack** [comment]
Our test plan for bare metal, replicating your work on CloudWatch, calls for permutations through log rate, log size, and pod count, so if I understand correctly that that is a full matrix of tests it would mean we want all three of those to be lists.
