### ISSUE TITLE
Remove Cerberus Checks

### ISSUE THREAD

**Issue by whitleykeith** [cloud-bulldozer/benchmark-operator#592]
We should remove Cerberus checks from Ripsaw. 

In the event that the Cluster is unhealthy there's a good chance that Ripsaw may not be able to take action on anything, including updating the state of the benchmark. Moreover, we haven't seen any benchmarks leverage this and so it may not be needed at this layer.

**Comment by jtaleric** [comment]
I am in-favor of removing this from Ripsaw... I know across the team we don't use this functionality.

**Comment by dry923** [comment]
+1 we don't use if for managed services either.

**Comment by jtaleric** [comment]
Let's get a PR to remove it. Thanks @whitleykeith !
