### ISSUE TITLE
pgbench pod enters into completed state during node failures

### ISSUE THREAD

**Issue by PrasadDesala** [cloud-bulldozer/benchmark-operator#603]
**Describe the bug**
When the postgres pod running node is rebooted, the pgbench pod which was in running state before the node reboot is immediately reaching completed state.

**To Reproduce**
1. Deploy Pgsql on OCS using ripsaw
2. Start running a benchmark by spinning postgres pod
3.  While the pgbench pod is in running state, reboot the node where postgres is running
4. Once the node is back to connectivity, the postgres pod is getting re-created and the pgbench reaches to completed state immediately. 

Logs of the pgbench pod shows empty without any data in it,
+----------+----------------+-------------+-------------+--------------+----------------+-------------+------------+----------+----------+
| pod_name | scaling_factor | num_clients | num_threads | trans_client | actually_trans | latency_avg | lat_stddev | tps_incl | tps_excl |
+----------+----------------+-------------+-------------+--------------+----------------+-------------+------------+----------+----------+
+----------+----------------+-------------+-------------+--------------+----------------+-------------+------------+----------+----------+

The result is empty and  nothing is running on it. 

**Expected behavior**
Pgbench should continue its run once the node is back online

**Comment by PrasadDesala** [comment]
@vasukulkarni FYI, as discussed I opened an issue here.

**Comment by jtaleric** [comment]
This isn't a bug, but a feature request. 

Ripsaw / Benchmarks are not meant to handle disaster / disaster recovery. For example, how long should the benchmark wait for the node to come back online?  

Also, if the node goes down in the middle of a write, do we need to clear the data in the DB before running the benchmark to get consistent results?

**Comment by rsevilla87** [comment]
I agree with @jtaleric, these kind of events during the workload, node reboots, network connectivity outages, etc haven't been tested and we can't provide an expected outcome of the benchmark during those, we'd need to implement a new logic to make benchmark-operator able to handle this kind of events.

Curious @PrasadDesala, what scenario are you trying to test here?

**Comment by PrasadDesala** [comment]
> I agree with @jtaleric, these kind of events during the workload, node reboots, network connectivity outages, etc haven't been tested and we can't provide an expected outcome of the benchmark during those, we'd need to implement a new logic in benchmark-operator to make it able to handle this kind of events.
> 
> Curious @PrasadDesala, what scenario are you trying to test here?

I am trying few failure scenarios on a node where Postgres is running which involves node reboot, drains and Postgres pod restart. During these operations it was observed that the pgbench benchmark pod is immediately going to completed state without running anything .
