### ISSUE TITLE
Uperf client pod did not created when using helm install

### ISSUE THREAD

**Issue by ebattat** [cloud-bulldozer/benchmark-operator#614]
**Describe the bug**
Uperf client pod did not created when using helm install

**To Reproduce**
Install benchmark operator using helm install
1. kubectl create -f uperf.yaml (use valid_uperd.yaml example: https://github.com/cloud-bulldozer/benchmark-operator/blob/master/tests/test_crs/valid_uperf.yaml )
2. Notice that uperf server pod is created properly
3. Notice that uperf client pod is not created.

Looks like that all stuck

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MuhammadMunir12** [comment]
@ebattat  I am facing the same issue and am already in the loop on this issue.  The issue is not yet solved. 
 #https://github.com/cloud-bulldozer/benchmark-operator/issues/646

**Comment by ebattat** [comment]
@MuhammadMunir12 Looks like I fix it in https://github.com/cloud-bulldozer/benchmark-operator/pull/663 (already merged)

**Comment by MuhammadMunir12** [comment]
@ebattat  Tried but didn't work for me.

**Comment by ebattat** [comment]
It works for me. Did you clone the latest repository ?

**Comment by MuhammadMunir12** [comment]
@ebattat  Yeah this one (https://github.com/cloud-bulldozer/benchmark-operator.git) but didn't work.

**Comment by MuhammadMunir12** [comment]
@ebattat Could you please share the steps you performed? I just to match if I've not missed anything. Thanks

**Comment by ebattat** [comment]
@MuhammadMunir12 
git clone https://github.com/cloud-bulldozer/benchmark-operator
cd benchmark-operator
make deploy
try to run test uperf: 
https://github.com/cloud-bulldozer/benchmark-operator/blob/master/tests/test_crs/valid_uperf.yaml

**Comment by bengland2** [comment]
I think I've seen this problem before, Shekhar used helm to deploy and the benchmark-operator-manager pod became the benchmark-operator pod.  I didn't get around to reporting it, just went to using make deploy.
