### ISSUE TITLE
E2E VM support: Adding E2E tests for VM workloads

### ISSUE THREAD

**Issue by ebattat** [cloud-bulldozer/benchmark-operator#631]
**Is your feature request related to a problem? Please describe.**
The current E2E tests supports Pod workloads only, I suggest to add also E2E support for VM workloads using cutting edge technology based on Python3/ Docker/ Github actions/ Terraform/ Cloud 

**Describe the solution you'd like**
The solution is to run smart E2E tests per each commit using Github actions for Pod and VM workloads using Azure cluster 
 preinstalled with CNV/OCS/ECK/Grafana. We plan to deploy a full cluster with preinstalled requirement using Terraform capabilities per run [estimation time for full deployment ~1 hour], for starter we will use stop/start mechanism for existing cluster for cost savings.  

**Describe alternatives you've considered**
The main goal is to run agile E2E tests for Pod and VM workloads for each branch commit using Github actions.
For each commit we will start Azure cluster and we will trigger E2E tests for VM and Pod to test the commit changes before it reach to review, also we can accelerate the E2E branch test time and trigger only the specific workload E2E test that changed.
We can use [benchmark-runner](https://github.com/redhat-performance/benchmark-runner) framework capabilities for running the E2E tests in agile smart way for each branch commit.
I can do a quick demo and share with you the details for my plan.   

**Additional context**
I have already shared some details with Raul and looks like it can be a perfect feature for running E2E tests for Pod and VM workloads.

**Comment by jtaleric** [comment]
Why do we need this `benchmark-runner`?

**Comment by jtaleric** [comment]
`[estimation time for full deployment ~1 hour]` - This is a bit concerning.

**Comment by ebattat** [comment]
Benchmark runner is a framework that gives an ability to run VM and Pod workloads in simple and smart way and that including configuration, recovery and validation mechanism. Also it gives you a simple workflow for adding a new workload.
We can try embedded it inside benchmark operator but that required maintenance for every enhancement inside benchmark-runner.

**Comment by sjug** [comment]
Hi @ebattat, thanks for the enhancement suggestion.

I'm not sure I'm clear on your suggestion:
> The current E2E tests supports Pod workloads only, I suggest to add also E2E support for VM workloads using cutting edge technology based on Python3/ Docker/ Github actions/ Terraform/ Cloud
- Which current e2e tests are you referring to the ones run on `benchmark-operator`?
- The change you're proposing is to add support for "VM workloads"?
- Given the "VM workloads" you're talking about are CNV in OpenShift, what would the practical difference be between a typical pod workload and a CNV pod VM workload?
- In regards to the cutting edge technology, are you suggesting we use GitHub actions to launch CI? 

> The solution is to run smart E2E tests per each commit using Github actions for Pod and VM workloads using Azure cluster
preinstalled with CNV/OCS/ECK/Grafana.
- Why specifically Azure?
- How are you preinstalling CNV/OCS/ECK/Grafana?

> We plan to deploy a full cluster with preinstalled requirement using Terraform capabilities per run [estimation time for full deployment ~1 hour], for starter we will use stop/start mechanism for existing cluster for cost savings.
- Are you talking about using the `openshift-installer` (which uses terraform) to deploy a cluster?

> We can use benchmark-runner framework capabilities for running the E2E tests in agile smart way for each branch commit.
I can do a quick demo and share with you the details for my plan.
- I'm not sure I see what we gain with the use of `benchmark-runner`? I've never seen this project before, but after a quick look it seems to be a python wrapper that deploys the `benchmark-operator`?

**Comment by learnitall** [comment]
There are three main points of concern that I have here. 

First, can you talk about the purpose behind benchmark-runner? I agree with @sjug that it looks like a wrapper around benchmark-operator. If this is the case, we **can not have** benchmark-runner be used for a CI for benchmark-operator. We faced this same problem with benchmark-wrapper where benchmark-wrapper's testing CI used benchmark-operator and this lead to circular dependency issues creating flaky results, as each CI run was testing benchmark-wrapper changes as well as how they integrated into benchmark-operator (i.e. we test benchmark-wrapper by using benchmark-operator which already depends on benchmark-wrapper).

Second, this seems to be three separate issues and associated PRs that you are suggesting. One is for testing VM workloads, one is for adding CI runs on each commit and one is for recreating the CI. I definitely would love to work with you to revisit the CI that we have in place and make improvements, but can we make sure that we take it one step at a time? Doing multiple large changes like this within the same context can get really messy really fast.

Third, and I already have this issue with our current CI which is why I'm bringing it up here, whatever CI solution we come up with needs to be cost effective, time efficient and easy to maintain. On-demand deployment of a cluster on Azure per-commit is super sick, but off the bat *sounds* like a time-sink. My initial thought is to use GHA to deploy a small [single node cluster](https://github.com/code-ready/snc) and then perform tiny benchmark workloads. 

I guess my overall questions are: where do you want to start and how can we modify your plan to be easier to maintain?

**Comment by ebattat** [comment]
Hi @sjug and @learnitall,

First thanks for reviewing my feature enhancement.
1. The main purpose of [benchmark-runner](https://github.com/redhat-performance/benchmark-runner) framework is for OpenShift CNV Performance benchmarks that placed on IBM cloud. The current CI is only for package unittest/ Integration/ E2E tests. Currently, benchmark-runner support Stressng, Uperf, Hammerdb(Mariadb,mssql, Postgres) on Pod and VM using OCS.
We plan to enrich it with more workloads in the near future (that will be very easy because we already implement agile infrastructure for adding new workloads)
In summarized, Benchmark-runner is not another wrapper, its independence framework with all the capabilities inside.

2. We can also add CI for benchmark-operator as we already have inside benchmark-runner for triggering integrations tests for every branch commit and that can shorten the merge and review time and ensure for stable release. But its a different subject and not related to CNV workload support. and for sure if we plan to add it it will be on separate phase.

3. OCP deployment from scratch can be time consuming, we can accelerate it by auto loading from existing images. but for the beginning we can use a start/stop mechanism for cost saving.

I plan to start it after getting green light from the team and decide what is the right way to implement it. I believe we will get more clear picture after internal meeting with @jtaleric team.

If you have more unclear things please let me know.

**Comment by ebattat** [comment]
Hi @sjug,
First thanks for reviewing my feature enhancement.

Please see my answers below:

**Which current e2e tests are you referring to the ones run on benchmark-operator?**
I mean to the tests that run against every commit change that related only to pod workloads.

**The change you're proposing is to add support for "VM workloads"?**
Yes, I want to add CNV workload tests that will run per commit. 

**Given the "VM workloads" you're talking about are CNV in OpenShift, what would the practical difference be between a typical pod workload and a CNV pod VM workload?**
The CNV workloads run on VM and not on Pod

In regards to the cutting edge technology, are you suggesting we use GitHub actions to launch CI?
Yes, I suggest that you will start use Github actions against branch and main that can shorten the merge and review time and ensure for stable release. 

**Why specifically Azure?**
Azure vm supports nested virtualization while AWS did not support.

**How are you preinstalled CNV/OCS/ECK/Grafana?**
We can use Terraform for deploying a fresh cluster from scratch and run CNV/OCS/ECK/Grafana deployment using helm but that can take ~1 hour. If we want to shorten the deployment time we can use Azure Python SDK for launching OCP cluster from existing images or simply use start/stop mechanism. all those tasks for cost saving, I think that it waste and not effective to hold a cluster for 24/7 only for CI purpose.

**Are you talking about using the openshift-installer (which uses terraform) to deploy a cluster?**
Yes, but we need to add also our own for it for CNV/OCS/ECK/Grafana deployment

**Which stop/start mechanism are you referring to?**
Azure Python SDK for stop/start vm.

**I'm not sure I see what we gain with the use of benchmark-runner? I've never seen this project before, but after a quick look it seems to be a python wrapper that deploys the benchmark-operator?**
The current state of benchmark-operator is that no test for CNV workload changes on one hand, and also not auto tests for each PR, all run in semi automate only after manual review and manual jenkins job triggering. I suggest to add Github actions that will run the test per branch commit as we use in benchmark-runner. 
  
The main purpose of benchmark-runner framework is for OpenShift CNV Performance benchmarks that placed on IBM cloud. The current CI is only for package unittest/ Integration/ E2E tests. Currently, benchmark-runner support Stressng, Uperf, Hammerdb(Mariadb,mssql, Postgres) on Pod and VM using OCS.
We plan to enrich it with more workloads in the near future (that will be very easy because we already implement agile infrastructure for adding new workloads)
In summarized, Benchmark-runner is not another wrapper, its independence framework with all the capabilities inside.

If you have more questions please dont hestitate to ask me.

**Comment by whitleykeith** [comment]
> The current state of benchmark-operator is that no test for CNV workload changes on one hand, and also not auto tests for each PR, all run in semi automate only after manual review and manual jenkins job triggering. I suggest to add Github actions that will run the test per branch commit as we use in benchmark-runner.

Sure, using Github Actions is good idea and I agree that we should look at making our CI better in general, but the idea that we should spin up Azure clusters or even use *any* type of cluster that's not ephemeral (i.e. minikube/kind/etc.) will not scale. I know that we currently do use a long-running openshift cluster to run these tests but IMO we should move away from that.

> In summarized, Benchmark-runner is not another wrapper, its independence framework with all the capabilities inside

If this is the case then why do you need benchmark-operator? I'm not against having a lightweight CLI tool to submit benchmarks and wait for them to complete, I have a PR for just that  https://github.com/cloud-bulldozer/benchmark-operator/pull/617. But that is a lot different than what the benchmark-runner does. If you guys want to depend on the operator then sure go ahead, but like @learnitall adding benchmark-runner to this repo will create a circular dependency and that causes headaches we don't want to revisit. 


My final thoughts are more wholistic to our testing in this repo but I think this highlights a problem of us throwing all of our tests into one big "e2e" bucket without taking the time to consider what we're testing and why. At the end of the day there's little reason why we can't simply run unit tests on the individual roles to assert that the templates render with our expected results. If you wanted to add unit tests for that then I'd say that's great! Unit tests require little to no environment setup and can execute in a trivial amount of time. The above PR I mentioned does exactly that and tests ~70% of the included code in <4min. Ultimately the benchmark-operator is just gonna take a Benchmark CR and translate it into raw manifests for the cluster. We don't need the cluster to assert that the raw manifests are what we expect. At that point we can probably reduce our current e2e tests to reduce the time it takes now (which is a very long time for an operator)

**Comment by ebattat** [comment]
Hi @whitleykeith ,

I agree and disagree with some point.
To have an unittest is best practice and I recommend to you it and try as you can to mock things. (i.e [benchmark runner unittest](https://github.com/redhat-performance/benchmark-runner/blob/main/tests/unittest/benchmark_runner/common/oc/test_oc.py#L33)
But you must have also integrations and E2E tests for stable release otherwise we will fail on real time run in benchmark CI.
I know that using a real cluster is cost effective and time consuming but that the only way to make sure our release is working without bugs that is a best practice in development world.

If you have more comments please let me know

**Comment by ebattat** [comment]
Hi All,

Here is the meeting summery with @jtaleric team:

We will create an isolate nightly CI using Azure cluster for all supported VM/Pod workloads in benchmark-runner.
Every night Benchmark-runner (using Github actions) will create an image using latest benchmark-operator and run E2E tests against Pod/VM workloads. In a case of failure a ticket will be raised in benchmark-operator Github issues.
I will the share with you more details once I will start work on it.

CI E2E Verification:
1. Benchmark controller manager running without errors
2. Each workload status create, initialized,ready, terminated per UUID.
3. VM/Pod reach to completed status without any errors per UUID.
4. Verified that data uploaded to ElasticSearch per UUID correctly.
5. System metrics works properly per UUID workload.
6. Benchmark controller manager terminated properly.

Please let me know that you are OK with the road map so I will start work on it.

**Comment by ebattat** [comment]
Hi @jtaleric and all,

We have a nightly CI run on the **latest** benchmark-operator that test Stressng, Uperf and hammerdb for Pod and CNV. It extracts the results into Grafana dashboard. later on we plan to add more workloads.

Here is the nightly CI path:
[Nightly CI](https://github.com/redhat-performance/benchmark-runner/actions/workflows/Nightly_Func_CI.yml)

If you have any questions regarding it please dont hesitate to ask me.
Also we can have a short demo session on it.

Best regards,
Eli Battat.
