### ISSUE TITLE
benchmark CRs should not be handled in parallel

### ISSUE THREAD

**Issue by mulbc** [cloud-bulldozer/benchmark-operator#635]
**Is your feature request related to a problem? Please describe.**
When creating two or more benchmark CRs, I expect these CRs to be handled after each other, not at the same time

**Describe the solution you'd like**
Keep all benchmark CRs in Pending or Waiting phase until one is finished, then activate the next CR.

**Describe alternatives you've considered**
You can write a script that continuously checks the benchmark CR, once it is finished it creates a new CR... This is possible but a) you need a workstation that always runs that script and b) this is what we have operators for

**Comment by jtaleric** [comment]
Understood. We do not have this logic, but to add this logic we would want to consider : https://github.com/cloud-bulldozer/benchmark-operator/issues/465

Not sure if the approach should be handle 1 CR at a time... or have the option to run multiple/single...

**Comment by bengland2** [comment]
So from a different perspective, I find it very useful to be able to run benchmark CRs at the same time.  Elko Kuric explained the utility of this feature. This allows us to test things like what happens to Cephfs if there is heavy RBD access simultaneous with it, or what happens to Ceph if the network is busy or there are a lot of PVs coming and going, for example.

It would be great if we could add a field that says "wait for benchmark name X to complete before running this", or something like that, that would satisfy this issue but also would continue to allow simultaneous workloads to be applied.   Thoughts?

**Comment by bengland2** [comment]
Chris, Joe's proposal #465 does allow for either parallel or serial execution.   I like inheriting some parameters of the benchmark suite down to the individual benchmarks, so I don't have to repeat parameters.  Examples: prometheus: section, elasticsearch: section.

Only thing that concerns me here is that the test uuid might be the same for all of the component tests, which could make it hard to pull  just the data for one individual test in the series from elasticsearch. It appears that the BenchmarkSuite could do this, but wanted to check with ripsaw team.   For example, if the benchmark suite name field is foo, then the benchmark name of the 2nd item in the list would be foo-2, and it would have a separate uuid from foo-1?

**Comment by mulbc** [comment]
I guess #465 would solve my issue then, thus closing this and will see if we can get this in soon
