### ISSUE TITLE
Trex Pod crashes due to invalid type casting

### ISSUE THREAD

**Issue by Tan2Pi** [cloud-bulldozer/benchmark-operator#659]
After removing elasticsearch from the trex template to avoid the bug discussed in #658, the trex pod successfully starts, but the trex pod crashes due to a type mismatch.  
  
Error from trex pod:  
```
oc logs -f trex-traffic-gen-pod-476d3c7c-b62bn
2021-08-26T16:52:46Z - INFO     - MainProcess - run_snafu: logging level is INFO
2021-08-26T16:52:46Z - INFO     - MainProcess - _load_benchmarks: Successfully imported 1 benchmark modules: uperf
2021-08-26T16:52:46Z - INFO     - MainProcess - _load_benchmarks: Failed to import 0 benchmark modules:
2021-08-26T16:52:46Z - INFO     - MainProcess - run_snafu: Not connected to Elasticsearch
Traceback (most recent call last):
  File "/usr/local/bin/run_snafu", line 33, in <module>
    sys.exit(load_entry_point('snafu', 'console_scripts', 'run_snafu')())
  File "/opt/snafu/snafu/run_snafu.py", line 166, in main
    for i in process_generator(index_args, parser):
  File "/opt/snafu/snafu/run_snafu.py", line 182, in process_generator
    for wrapper_object in benchmark_wrapper_object_generator:
  File "/opt/snafu/snafu/run_snafu.py", line 216, in generate_wrapper_object
    benchmark_wrapper_object = wrapper_factory(index_args.tool, parser)
  File "/opt/snafu/snafu/utils/wrapper_factory.py", line 53, in wrapper_factory
    wrapper_obj = wrapper(parser)
  File "/opt/snafu/snafu/trex_wrapper/trex_wrapper.py", line 42, in __init__
    self._set_cfg()
  File "/opt/snafu/snafu/trex_wrapper/trex_wrapper.py", line 49, in _set_cfg
    core_list = list(map(int, c_list))
ValueError: invalid literal for int() with base 10: '0-111'
```

**Comment by mkarg75** [comment]
Hey Tan2Pi,

could you please provide your CR so I can compare with mine? Tres starts and finishes fine here.
Thanks!

**Comment by rsevilla87** [comment]
the error comes from this line: https://github.com/cloud-bulldozer/benchmark-wrapper/blob/master/snafu/trex_wrapper/trex_wrapper.py#L49
which is directly related with the configuration you pass to the oslat benchmark, as @mkarg75 we'd need the CR to have more insight.

**Comment by Tan2Pi** [comment]
Here is the Performance Profile CR:  
```
Spec:
  Additional Kernel Args:
    nmi_watchdog=0
    audit=0
    mce=off
    processor.max_cstate=1
    idle=poll
    intel_idle.max_cstate=0
  Cpu:
    Isolated:  4-55,60-111
    Reserved:  0,56,1,57,2,58,3,59
  Hugepages:
    Default Hugepages Size:  1G
    Pages:
      Count:  16
      Size:   1G
  Node Selector:
    node-role.kubernetes.io/master:
  Numa:
    Topology Policy:  restricted
  Real Time Kernel:
    Enabled:  false
```

Here is the TestPMD CR:  
```
kind: Benchmark
metadata:
  name: testpmd-benchmark
  namespace: benchmark-operator
spec:
  clustername: 176b
  workload:
    name: testpmd
    args:
      privileged: true
      pin: true
      pin_testpmd: "etcd-0.oss.labs"
      pin_trex: "etcd-1.oss.labs"
      networks:
        testpmd:
          - name: dpdk-network
            count: 2  # Interface count, Min 2
        trex:
          - name: dpdk-network
            count: 2
```
I'm attempting to run this benchmark on Mellanox CX-5 25G NICs, FYI.
Here is the SR-IOV Network Node Policy:  
```
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: mlx-dpdk-network-node-policy
  namespace: openshift-sriov-network-operator
spec:
  deviceType: netdevice
  isRdma: true
  linkType: eth
  nicSelector:
    pfNames:
    - eno12409
    rootDevices:
    - "0000:31:00.1"
  nodeSelector:
    node-role.kubernetes.io/master: ""
  numVfs: 20
  priority: 99
  resourceName: mlx_dpdk
```
And here is the SR-IOV Network being used:  
```
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: dpdk-network
  namespace: openshift-sriov-network-operator
  uid: eb39ce49-da0c-42ae-9437-a538703b6d3c
spec:
  ipam: |-
    {
      "type": "whereabouts",
      "range": "10.57.1.0/24"
    }
  networkNamespace: benchmark-operator
  resourceName: mlx_dpdk
```

**Comment by mukrishn** [comment]
@Tan2Pi from the trex error message `ValueError: invalid literal for int() with base 10: '0-111'` it seems like your PAO profile was not applied properly or not using the right worker node for this pod, as we see it didn't not pin CPUs and it included complete pool of `reserved` core(0-111) to the pod, hence the script couldn't parse the CPU cores(from this file `/sys/fs/cgroup/cpuset/cpuset.cpus`) to run the trex server. 
In ideal scenario, this file will hold all the allocated cpu for that pod(for ex - 10,12,14,16) but in our case it is 0-111 which is not expected by the script.
Also its recommended to isolate CPUs from the same NUMA(from the socket in which your physical NIC is attached to) for the pods. In our [doc](https://github.com/cloud-bulldozer/benchmark-operator/blob/master/docs/testpmd.md#sample-pao-configuration), we have isolated all CPU from a socket(socket of our NIC) and reserved others for house keeping process. 
Could you check your PAO profile has applied on the node `etcd-1.oss.labs` properly and also give a try with updated PAO once ?

**Comment by Tan2Pi** [comment]
Yep, this seems to have been an issue with the PAO, it doesn't seem like CPU pinning using the PAO works with a 3 node cluster. Running this benchmark on worker nodes cleared up the issue seen here, thanks for the help!
