### ISSUE TITLE
Fio nodeselector

### ISSUE THREAD

**Issue by jeniferh** [cloud-bulldozer/benchmark-operator#681]
**Describe the bug**
Currently the fio sample CR still uses "pin_server": https://github.com/cloud-bulldozer/benchmark-operator/blob/master/config/samples/fio/cr.yaml#L26
but as mentioned in the doc, the param has been replaced w/ nodeselector: https://github.com/cloud-bulldozer/benchmark-operator/blob/master/roles/fio_distributed/templates/servers.yaml#L46

(also the fio server_vm template does not have any pinning logic, I will fix that w/ a PR soon, working on refactoring the vm case a bit..)

What I am not sure about is how we would want to expose the nodeselector param in the sample CR, because for ex. if you add an empty hostname selector the scheduling will fail:
```
      # put all fio pods on this server
      nodeselector:
        kubernetes.io/hostname: ''
```
Would it be better to add that above example but just commented out by default in the sample CR?

**Comment by jeniferh** [comment]
@bengland2  thoughts?

**Comment by bengland2** [comment]
@jeniferh I agree, I did not see your "at" notification.   if a parameter isn't typically used in a benchmark, remove it from the only example of the benchmark CR.   If someone wants to add additional examples with some comments to explain why they are there, that's different.   I never use pin_server, but in cases where there is only 1 node with the type of storage device that you want to use, that might be why it's there?

As for node selector, I think it would be useful to have a way to constrain nodes that the fio pods run on, but the default should still be to run them anywhere.  Perhaps the node selector could be a "blacklist" label that means "dont run them on nodes with this label".   If you don't put the label anywhere, then behavior is same as it is today, and the label could be an existing label such as cluster.ocs.openshift.io/openshift-storage, which would mean "dont run fio pods where OCS is running", which is the opposite of hyperconverged.   blacklisting is similar to "oc adm cordon" but less of a sledgehammer.
