### ISSUE TITLE
iperf3 pod doesn't get attached PVC

### ISSUE THREAD

**Issue by MuhammadMunir12** [cloud-bulldozer/benchmark-operator#689]
I was just curious to try out that using the iperf3 benchmark, can we even add PVC to server and client pods?

**Comment by MuhammadMunir12** [comment]
Also I was testing a scenario by limiting the resources for server and client pods in iperf3 but those doesn't get applied as well.

**Comment by MuhammadMunir12** [comment]
@jtaleric @mukrishn  any comments please?

**Comment by rsevilla87** [comment]
Hey @MuhammadMunir12 , with the current implementation is not possible to do any of those actions. It will require some changes in the code.
