### ISSUE TITLE
Post_sleep sets always the benchmark as succeded

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/benchmark-operator#692]
Hey @dry923 @morenod , I've detected an issue with caused by the sleep command at the end of the scale workload.

https://github.com/cloud-bulldozer/benchmark-operator/blob/52d83ae122f411c3eaaf4df53b43fca717b6fe40/roles/scale_openshift/templates/scale.yml#L76-L86

Due to this command the benchmark is always set as succeeded even when the benchmark has actually failed. That is a bit problematic since we're not able to detect when the workload finished correctly by just checking the Benchmark status.

**Comment by morenod** [comment]
fixed #694

**Comment by morenod** [comment]
closes #694
