### ISSUE TITLE
benchmark-operator does not detect workload failure and continues running

### ISSUE THREAD

**Issue by RobertKrawitz** [cloud-bulldozer/benchmark-operator#705]
**Describe the bug**
benchmark-operator does not notice that a workload has gone into Error state, and keeps waiting indefinitely.

**To Reproduce**
Workload that goes into an error state as in https://github.com/cloud-bulldozer/benchmark-wrapper/issues/372

**Expected behavior**
benchmark-operator should notice that the workload failed and clean up (or perhaps if requested log a notice of the failure and wait, rather than retrying anything).

**Screenshots**
Notice that the workload pod has gone into Error state, but the benchmark-operator continues to accumulate log data (ansible-playbook output):

```
[root@perf-sm5039-3-1 benchmark-runner]# oc get pod
NAME                                            READY   STATUS      RESTARTS   AGE
benchmark-controller-manager-7c9ff9796b-ts5pm   2/2     Running     0          68m
hammerdb-kata-creator-27917bd1--1-mv7hb         0/1     Completed   0          67m
hammerdb-kata-workload-27917bd1--1-swjfq        0/1     Error       0          63m
system-metrics-collector-27917bd1--1-zmwrq      0/1     Completed   0          63m
[root@perf-sm5039-3-1 benchmark-runner]# oc logs benchmark-controller-manager-7c9ff9796b-ts5pm |less
error: a container name must be specified for pod benchmark-controller-manager-7c9ff9796b-ts5pm, choose one of: [manager redis-master]
[root@perf-sm5039-3-1 benchmark-runner]# oc logs benchmark-controller-manager-7c9ff9796b-ts5pm -c manager |wc
 150929  423796 13223513
[root@perf-sm5039-3-1 benchmark-runner]# oc logs benchmark-controller-manager-7c9ff9796b-ts5pm -c manager |wc
 157355  441694 13789861
```

**Comment by RobertKrawitz** [comment]
@ebattat

**Comment by ebattat** [comment]
There is timeout after 1 hour. We can add check status for error and raise it once it happened.
