### ISSUE TITLE
ripsaw cli k8s client does not honor proxy settings

### ISSUE THREAD

**Issue by mffiedler** [cloud-bulldozer/benchmark-operator#726]
In clusters accessible only via proxy, the e2e-benchmark tests using the ripsaw cli fail when oc otherwise works. The client needs to be updated to configure the kubernetes.client with the proxy. Something like this, I think:

    config.load_kube_config(config_file=kubeconfig_path)
    proxy_url = os.getenv('http_proxy', None)
    if proxy_url:
       client.Configuration._default_proxy = proxy_url
    self.api_client = client.ApiClient()
I will try to put up a PR if I can figure out how to test ripsaw CLI changes locally (easily)

**Comment by rsevilla87** [comment]
This issue has been fixed by #729
