### ISSUE TITLE
benchmark-runner: CNV nightly CI failed in Uperf vm workload

### ISSUE THREAD

**Issue by ebattat** [cloud-bulldozer/benchmark-operator#761]
**Describe the bug**
benchmark-runner nightly CI [failed](https://github.com/redhat-performance/benchmark-runner/actions/runs/2388587004) in Uperf vm 

**To Reproduce**
1. Run uperf vm 
2. Server vm running
3. Client vm did not scheduled
failed to ensurePod benchmark-operator/virt-launcher-uperf-client-10.130.0.92-cb4bf5f6-p7dqt since it is not yet scheduled

Suspect PR: https://github.com/cloud-bulldozer/benchmark-operator/pull/755/files
Starting failing [today](https://github.com/redhat-performance/benchmark-runner/actions/workflows/Nightly_Func_Env_CI.yml)

**Comment by rsevilla87** [comment]
Seems your PR is somehow affecting CNV based benchmarks @smalleni

**Comment by ebattat** [comment]
Here is the the running flow:

**Comment by smalleni** [comment]
It's probably because I create a different configmap for each client pod?

**Comment by smalleni** [comment]
@ebattat Is there anything in that PR that would affect CNV workloads, I'm not quite familiar how CNV uses the uperf workload. I remember giving @jeniferh a headsup up about this nodeport pr...

**Comment by smalleni** [comment]
@ebattat The only change I assume could affect you is that we now create a different configmap per pod and change its name:

**Comment by smalleni** [comment]
This probably needs updating: https://github.com/cloud-bulldozer/benchmark-operator/blob/master/roles/uperf/templates/workload_vm.yml.j2#L92 let's try that.

**Comment by ebattat** [comment]
Ok I will check.
