### ISSUE TITLE
All client and Server pods are scheduled to the different nodes with 2pairs of server and client scenario

### ISSUE THREAD

**Issue by SachinNinganure** [cloud-bulldozer/benchmark-operator#800]
the document says "https://github.com/cloud-bulldozer/benchmark-operator/blob/master/docs/uperf.md"

By default, the uperf server and client pods will be preferably scheduled on different nodes, thanks to a podAntiAffinity rule. In scenarios with more than 1 pair, all clients and servers will be scheduled to the same node.

But one of the uperf tests I observed :
Running a scenario with 2 pairs!!!
[sninganu@sninganu ~]$ oc get pods -owide
NAME                                            READY   STATUS    RESTARTS   AGE     IP            NODE                                 NOMINATED NODE   READINESS GATES
backpack-7d4e42be-7cmgl                         1/1     Running   0          9m      10.131.0.26   sn-npt-ibm412-bcxr8-worker-1-nxqvc   <none>           <none>
backpack-7d4e42be-h4zb5                         1/1     Running   0          9m      10.128.2.21   sn-npt-ibm412-bcxr8-worker-2-ch7ct   <none>           <none>
backpack-7d4e42be-hr7nz                         1/1     Running   0          9m      10.129.0.39   sn-npt-ibm412-bcxr8-master-1         <none>           <none>
backpack-7d4e42be-ktjvb                         1/1     Running   0          9m      10.128.0.53   sn-npt-ibm412-bcxr8-master-2         <none>           <none>
backpack-7d4e42be-qjjph                         1/1     Running   0          9m      10.130.0.62   sn-npt-ibm412-bcxr8-master-0         <none>           <none>
backpack-7d4e42be-wgtwn                         1/1     Running   0          9m      10.129.2.14   sn-npt-ibm412-bcxr8-worker-3-sw9vf   <none>           <none>

benchmark-controller-manager-7d694c6b9c-tspwh   2/2     Running   0          10m     10.131.0.25   **sn-npt-ibm412-bcxr8-worker-1-nxqvc**   <none>           <none>
uperf-client-172.30.123.203-7d4e42be-sppdp      1/1     Running   0          7m5s    10.131.0.28   sn-npt-ibm412-bcxr8-worker-1-nxqvc   <none>           <none>
uperf-client-172.30.223.179-7d4e42be-7wblr      1/1     Running   0          7m6s    10.131.0.27   **sn-npt-ibm412-bcxr8-worker-1-nxqvc**   <none>           <none>
uperf-server-0-7d4e42be-hsc25                   1/1     Running   0          7m38s   10.128.2.22   **sn-npt-ibm412-bcxr8-worker-2-ch7ct**   <none>           <none>
uperf-server-1-7d4e42be-twkdq                   1/1     Running   0          7m38s   10.128.2.23   **sn-npt-ibm412-bcxr8-worker-2-ch7ct**   <none>           <none>

I triggered a test for **2pairs** and could see that the server and client pods are scheduled on **different** nodes as above;
test
→ https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/network-perf/372/parameters/

**Comment by jtaleric** [comment]
>  In scenarios with more than 1 pair, all clients and servers will be scheduled to the same node.

All the clients will be schedule to the same node, as well as the servers. How many nodes did your env have?

**Comment by SachinNinganure** [comment]
3 worker and 3 master nodes.
